version: "3.4"
services:
  app:
    image: bmeme/node-dev:14.15.4-buster-slim
    entrypoint: /bin/sleep infinity
    working_dir: /usr/src/app/
    volumes:
      - "../app:/usr/src/app:cached"
    environment:
      - DNSDOCK_ALIAS=${PROJECT_NAME}.${PROJECT_VENDOR}.docker
